site_name: Signal SDK
repo_url: https://github.com/SignalOceanSdk/SignalSDK
edit_uri: ""
theme:
  name: material
  favicon: img/favicondark.ico
  logo: img/favicondark.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
nav:
    - 'index.md'
    - APIs Documentation:
      - 'historical_tonnage_list.md'
      - 'voyages.md'
      - 'vessels.md'
extra_css:
  - css/site.css
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
plugins:
  - mkdocs-jupyter
  - search
  - mkdocstrings
  