site_name: Signal SDK
repo_url: https://github.com/SignalOceanSdk/SignalSDK
edit_uri: ""
theme:
  name: material
  favicon: img/favicondark.ico
  logo: img/favicondark.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
nav:
    - 'index.md'
    - Historical Tonnage List (deprecated):
      - 'historical_tonnage_list.md'
    - Tonnage List:
      - 'tonnage_list.md'
      - Examples:
        - 'examples/jupyter/Tonnage List API/Historical analysis over all vessels.ipynb'
        - 'examples/jupyter/Tonnage List API/Working with the TonnageListAPI.ipynb'
        - 'examples/jupyter/Tonnage List API/Persisting data in SQLite.ipynb'
        - 'examples/jupyter/Tonnage List API/Finding vessels that were on subs around Houston.ipynb'
        - 'examples/jupyter/Tonnage List API/Finding vessels that were opening at Fos.ipynb'
    - Voyages:
      - 'voyages.md'
      - Examples:
        - 'examples/jupyter/VoyagesAPI/VoyagesAPI-UseCases.ipynb'
        - 'examples/jupyter/VoyagesAPI/VoyagesAPI.ipynb'
        - 'examples/jupyter/VoyagesAPI/VoyagesAPI-VoyagesDataLike.ipynb'
        - 'examples/jupyter/VoyagesAPI/Port Congestion.ipynb'
    - OilX Cargo Tracking:
      - 'oilx_cargoes.md'
      - Examples:
        - 'examples/jupyter/OilXCargoTrackingAPI/OilX Cargo Tracking API.ipynb'
    - Vessels:
      - 'vessels.md'
      - Examples:
        - 'examples/jupyter/VesselsAPI/VesselsAPI.ipynb'
    - Companies:
      - 'companies.md'
      - Examples:
        - 'examples/jupyter/CompaniesAPI/CompaniesAPI.ipynb'
    - Distances:
      - 'distances.md'
      - Examples:
        - 'examples/jupyter/DistancesAPI/QuickStartDistancesAPI.ipynb'
        - 'examples/jupyter/DistancesAPI/DistancesWithRouteExample.ipynb'
        - 'examples/jupyter/DistancesAPI/AlternativeRoutes.ipynb'
    - Port Expenses:
      - 'port_expenses.md'
      - Examples:
        - 'examples/jupyter/PortExpensesAPI/PortExpensesAPI.ipynb'
    - Market Rates:
      - 'market_rates.md'
      - Examples:
        - 'examples/jupyter/MarketRatesAPI/MarketRatesAPI.ipynb'
    - Freight Rates:
      - 'freight_rates.md'
      - Examples:
        - 'examples/jupyter/FreightRatesAPI/FreightRatesAPI.ipynb'
    - Combined Examples:
      - Examples:
        - 'examples/jupyter/Combined Examples/CargoFlows.ipynb'
        - 'examples/jupyter/Combined Examples/Supply trend with market rates.ipynb'
    - Release notes:
      - 'releases/Version 1.0.4.md'
      - 'releases/Version 1.0.3.md'
      - 'releases/Version 1.0.2.md'
      - 'releases/Version 1.0.1.b6.md'
extra_css:
  - css/site.css
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
plugins:
  - mkdocs-jupyter
  - search
  - mkdocstrings
