name: ci
on:
  push:
    branches:
      - feature/PT-3741-GitHub-docs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install mkdocs            
          pip install mkdocs-material   
          pip install mkdocstrings      
          pip install mkdocs-jupyter
          pip install requests
      - name: Deploy docs
        run: mkdocs gh-deploy --force